# =============================================================================
# Gateway Resource - Your Cloud Load Balancer Entry Point
# =============================================================================
#
# NETWORK ANALOGY: Think of this as configuring a hardware load balancer.
# - The Gateway is like an F5 or NetScaler virtual server
# - Listeners are like VIPs (Virtual IPs) with specific ports
# - Each listener accepts traffic and routes it based on HTTPRoutes
#
# PREREQUISITE: Create the TLS secret BEFORE applying this file:
#
#   openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#     -keyout /tmp/tls.key -out /tmp/tls.crt \
#     -subj "/CN=*.local.dev" \
#     -addext "subjectAltName=DNS:*.local.dev,DNS:localhost"
#
#   kubectl create secret tls eg-tls-cert \
#     --cert=/tmp/tls.crt --key=/tmp/tls.key \
#     -n envoy-gateway-system
#
# =============================================================================

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-gateway
  namespace: envoy-gateway-system   # Must be in the same namespace as Envoy Gateway
spec:
  gatewayClassName: eg              # References the GatewayClass (like selecting your LB vendor)
  listeners:
    # HTTP Listener - accepts unencrypted traffic on port 80
    # Similar to: virtual server 0.0.0.0:80 on a traditional load balancer
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All                 # Accept routes from any namespace

    # HTTPS Listener - terminates TLS on port 443
    # Similar to: SSL offloading on a hardware load balancer
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate             # TLS termination (decrypt here, plain HTTP to backend)
        certificateRefs:
          - name: eg-tls-cert       # Reference to the TLS secret created above
            kind: Secret
