# =============================================================================
# TLSRoute - TLS Passthrough Routing (SNI-based) - COMPLETE EXAMPLE
# =============================================================================
#
# NETWORK ANALOGY: Like SSL/TLS passthrough on a load balancer.
# - Traffic stays encrypted end-to-end
# - Gateway routes based on SNI (Server Name Indication) header
# - Backend handles TLS termination (not the Gateway)
#
# COMPARISON:
# - HTTPRoute + Gateway TLS: Gateway terminates TLS, inspects HTTP, re-encrypts
# - TLSRoute: Gateway does NOT decrypt, just routes based on SNI
#
# USE CASES:
# - Backend requires end-to-end encryption (compliance, security)
# - Backend has its own certificate (can't share with Gateway)
# - mTLS between client and backend
# - Performance: avoid double encryption/decryption
#
# REQUIREMENTS:
# - Experimental Gateway API CRDs must be installed
# - Gateway listener must use mode: Passthrough
# - Backend must handle TLS termination
#
# =============================================================================

# -----------------------------------------------------------------------------
# STEP 1: Create backend TLS certificate (run this first!)
# -----------------------------------------------------------------------------
#
# Before applying this file, create the backend certificate:
#
#   openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#       -keyout /tmp/backend-tls.key -out /tmp/backend-tls.crt \
#       -subj "/CN=secure.local.dev" \
#       -addext "subjectAltName=DNS:secure.local.dev,DNS:localhost"
#
#   kubectl create secret tls backend-tls-cert \
#       --cert=/tmp/backend-tls.crt \
#       --key=/tmp/backend-tls.key \
#       -n demo-app
#
#   rm -f /tmp/backend-tls.key /tmp/backend-tls.crt
#
# -----------------------------------------------------------------------------

---
# Nginx configuration for HTTPS backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tls-config
  namespace: demo-app
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name secure.local.dev;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            return 200 'Hello from TLS Passthrough Backend!\nThe Gateway did NOT decrypt this traffic.\nYour connection is end-to-end encrypted.\n';
            add_header Content-Type text/plain;
        }
    }

---
# TLS-enabled backend deployment (nginx serving HTTPS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-tls
  namespace: demo-app
  labels:
    app: webapp-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-tls
  template:
    metadata:
      labels:
        app: webapp-tls
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 443
              name: https
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/nginx/ssl
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: tls-certs
          secret:
            secretName: backend-tls-cert    # Created manually above
        - name: nginx-config
          configMap:
            name: nginx-tls-config

---
# Service for the TLS backend
apiVersion: v1
kind: Service
metadata:
  name: webapp-tls-service
  namespace: demo-app
spec:
  selector:
    app: webapp-tls
  ports:
    - port: 443
      targetPort: 443
      name: https

---
# Gateway with TLS Passthrough listener
# This Gateway does NOT terminate TLS - it just forwards based on SNI
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-gateway-passthrough
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
    - name: tls-passthrough
      protocol: TLS
      port: 8443                    # Different port to avoid conflict
      tls:
        mode: Passthrough           # KEY: Don't decrypt, just forward
      allowedRoutes:
        namespaces:
          from: All

---
# TLSRoute - Routes encrypted traffic based on SNI hostname
# NOTE: This is v1alpha2 (experimental API)
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: secure-app-route
  namespace: demo-app
spec:
  parentRefs:
    # Attach to the passthrough Gateway listener
    - name: eg-gateway-passthrough
      namespace: envoy-gateway-system
      sectionName: tls-passthrough  # Must match listener name

  hostnames:
    # SNI hostname to match (client sends this in TLS ClientHello)
    - "secure.local.dev"

  rules:
    - backendRefs:
        # Backend must be running a TLS server
        # Traffic arrives still encrypted - backend decrypts it
        - name: webapp-tls-service
          port: 443

# =============================================================================
# HOW TO TEST:
# =============================================================================
#
# 1. First, create the backend TLS certificate (see STEP 1 above)
#
# 2. Apply this file:
#    kubectl apply -f 09-tlsroute-passthrough.yaml
#
# 3. Wait for resources to be ready:
#    kubectl wait --timeout=60s -n demo-app deployment/webapp-tls --for=condition=Available
#    kubectl wait --timeout=2m -n envoy-gateway-system gateway/eg-gateway-passthrough --for=condition=Programmed
#
# 4. Get the Gateway IP:
#    PASSTHROUGH_IP=$(kubectl get gateway/eg-gateway-passthrough -n envoy-gateway-system \
#                     -o jsonpath='{.status.addresses[0].value}')
#
# 5. Test with curl:
#    curl -k --resolve secure.local.dev:8443:$PASSTHROUGH_IP https://secure.local.dev:8443/
#
# Expected output:
#    Hello from TLS Passthrough Backend!
#    The Gateway did NOT decrypt this traffic.
#    Your connection is end-to-end encrypted.
#
# 6. VERIFY it's passthrough (check the certificate is from backend, not Gateway):
#    echo | openssl s_client -connect $PASSTHROUGH_IP:8443 -servername secure.local.dev 2>/dev/null \
#         | openssl x509 -noout -subject
#
#    Expected: subject=CN = secure.local.dev  (backend's cert, not Gateway's)
#
# =============================================================================
# CLEANUP:
# =============================================================================
#
# kubectl delete -f 09-tlsroute-passthrough.yaml
# kubectl delete secret backend-tls-cert -n demo-app
#
# =============================================================================
